---
- import_tasks: Deploy_ZabbixAgent2.yml
  when: (install_zabbix | default('NO') | upper) == "YES"

- import_tasks: deploy_monitor_process.yml
  when: (install_zabbix | default('NO') | upper) == "YES"


