---
# Variables por defecto
nessus_force_reinstall: true
nessus_manager_host: "10.181.8.192"
nessus_manager_port: 8834
nessus_agent_key: "279fa0cfb3549180f65cffe7a095455a4ba825af6ed6ad923cb7f228870a1694"
nessus_agent_groups: "corbeta"  # opcional
nessus_try_link: true
nessus_force_relink: false
nessus_cli_path: "/opt/nessus_agent/sbin/nessuscli"

# Carpeta de instaladores (relativa al rol)
nessus_installers_dir: "{{ role_path }}/files/installers"

# Carpeta FIJA de reportes en el controlador
nessus_output_dir: "/data/work/Salida_Instalacion_Agentes"

# Mapa de selecci√≥n por SO
nessus_pkg_dir_map:
  RedHat-7: "rhel7"
  RedHat-8: "rhel8"
  RedHat-9: "rhel9"
  OracleLinux-7: "rhel7"
  OracleLinux-8: "rhel8"
  OracleLinux-9: "rhel9"
  Suse-12: "sles12"
  Suse-15: "sles15"
  Debian-any: "debian"
  Ubuntu-any: "ubuntu"
  Fedora-any: "fedora"
  Amazon-any: "amazon"

# Ruta remota del instalador
nessus_installer_dest_dir: "{{ ansible_env.HOME }}"

# Control de acciones opcionales
nessus_audit_restart_service: false
nessus_audit_try_link: false

# Script Excel dentro del rol (NO se copia, se ejecuta directo con role_path)
nessus_excel_script_path: "{{ role_path }}/files/nessus_excel_report.py"
nessus_json_filename: "nessus_results.json"
nessus_excel_filename: "nessus_agent_reporte.xlsx"
